extends SceneTree
const Attention := preload("res://presentation/story_attention.gd")
const Lessons := preload("res://childhood/lesson_direction.gd")
var passed := 0
var failed := 0
func check(value: bool, label: String) -> void:
	if value: passed += 1
	else:
		failed += 1
		push_error("FAIL: " + label)
func _initialize() -> void:
	var flow := Attention.new()
	flow.enter_context("tracking", 0)
	flow.offer("Buddh · Bent reeds cross the print.", 0)
	var duration: int = Attention.reading_ticks("Buddh · Bent reeds cross the print.")
	check(not flow.read(duration - 1).is_empty(), "observation remains through its reading window")
	check(flow.read(duration).is_empty(), "finished observation yields a quiet screen")
	flow.offer("Buddh · Bent reeds cross the print.", duration + 1)
	check(flow.read(duration + 1).is_empty(), "unchanged text cannot loop itself forever")
	flow.offer("Buddh · The grass is pressed ahead.", 400)
	flow.offer("Buddh · Look first, then answer.", 401, Attention.STORY)
	check(flow.read(401).contains("grass"), "incidental reaction cannot interrupt an examined clue")
	flow.offer("Buddh · I found another mark.", 402)
	check(flow.read(402).contains("another"), "new deliberate observation has immediate feedback")
	check(flow.pending_count() == 0, "new interaction removes superseded incidental line")
	flow.offer("A quiet reflection.", 403, Attention.STORY)
	flow.offer("A second reflection.", 404, Attention.STORY)
	flow.offer("A third reflection.", 405, Attention.STORY)
	check(flow.pending_count() == 2, "incidental backlog is bounded")
	flow.enter_context("active", 406)
	check(flow.read(406).is_empty() and flow.pending_count() == 0, "threat entry removes all unrelated speech")
	flow.offer("Guard [Q], or get clear.", 406, Attention.DANGER)
	flow.offer("Another trail observation.", 407, Attention.ACCOUNT)
	check(flow.read(407).contains("Guard"), "urgent strike remains ahead of lower priority information")
	flow.enter_context("escaped:accounts", 408)
	check(flow.read(408).is_empty() and flow.pending_count() == 0, "safety cannot inherit combat instructions")
	flow.offer("Buddh · Home again.", 408)
	check(flow.read(408) == flow.read(408), "sampling paused tick never consumes dialogue")
	var memory := flow.history()
	memory.clear()
	check(not flow.history().is_empty(), "presentation recall is copied rather than mutable shared history")
	flow.offer("", 409)
	check(flow.read(409).is_empty(), "explicit silence clears speech and backlog")
	flow.offer("Retained before rewind.", 410)
	flow.read(2)
	check(flow.history().is_empty() and flow.read(2).is_empty(), "rewinding drops dialogue from discarded time")
	for i in range(20): flow.offer("Observed line %d" % i, 10 + i)
	check(flow.history().size() == 12 and flow.history()[0] == "Observed line 8", "recall has finite ordered retention")
	flow.reset(30)
	check(flow.history().is_empty() and flow.pending_count() == 0 and flow.read(30).is_empty(), "loading reset clears all transient attention")
	check(Attention.reading_ticks("Short.") >= 180, "short lines have a readable floor")
	check(Attention.reading_ticks("word ".repeat(300)) <= 720, "long text has a bounded display and recall fallback")
	flow.offer("Primary account.", 30)
	flow.offer("A stale reflection.", 31, Attention.STORY)
	check(flow.read(800).is_empty(), "stale incidental cue is discarded rather than played late")
	check(Lessons.transition_line("ready", "active").is_empty(), "no invented omniscient attack prediction")
	check(Lessons.transition_line("sparring", "tracking").contains("Look first"), "lesson motif carries to the trail")
	check(Lessons.transition_line("escaped:return", "escaped:complete").contains("could see"), "resolution pays off observation without a culprit")
	print("STORY_ATTENTION_TESTS: %d passed, %d failed" % [passed, failed])
	quit(1 if failed else 0)
