extends "res://tests/test_shah_road.gd"
## Static geometry/source tests plus a genuine input-driven interior walk.
const Setting := preload("res://territory/settlement/gujranwala_setting.gd")
const SETTING_SAVE := "user://gujranwala-setting-regression-only.json"

func _run() -> void:
	var catalogue: Dictionary=JSON.parse_string(FileAccess.get_file_as_string(Setting.RESEARCH_PATH))
	check(catalogue.schema=="1792.setting-research.v1","versioned source catalog")
	check(catalogue.surveyed_plan_available==false,"no fictional cadastral accuracy")
	check(catalogue.coordinate_basis=="authored_compressed_local_metres_not_georeferenced","authored coordinates declared")
	var ids: Array=[]
	for source in catalogue.sources:
		check(source.id not in ids,"unique source identity")
		ids.append(source.id)
		check(str(source.url).begins_with("https://"),"source address retained")
		check(not str(source.locator).is_empty() and not str(source.does_not_support).is_empty(),"scope and uncertainty accompany source")
	for feature in catalogue.features:
		for id in feature.source_ids: check(id in ids,"feature source reference resolves")
		check(not str(feature.basis).is_empty(),"feature admission declares source or authoring basis")
	check(catalogue.excluded_from_childhood_build.size()==3,"later-period material not silently backdated")
	var home:=Launch.make_world()
	var scene=home.get_node("ChildhoodChapter")
	scene.save_path=SETTING_SAVE
	root.add_child(home)
	await frames(5)
	var manifest: Dictionary=scene.setting.manifest.duplicate(true)
	check(manifest.id==Setting.ID and manifest.seed==Setting.SEED,"setting identity and seed")
	check(manifest.surveyed==false and manifest.horizon_is_playable==false,"backdrop is not a second streamed region")
	check(manifest.pieces>100 and manifest.pieces<180,"bounded detail count")
	check(scene.setting.get_node("StoreBack") is StaticBody3D,"store walls have real collision")
	check(scene.setting.get_node("StoreRoof") is StaticBody3D,"roof has real collision")
	var ray:=PhysicsRayQueryParameters3D.create(Vector3(-18,0.65,9),Vector3(-13,0.65,9),1)
	var hit: Dictionary=scene.get_world_3d().direct_space_state.intersect_ray(ray)
	check(not hit.is_empty() and hit.collider.name=="CourtyardWell","well central collider prevents decorative hole falling")
	# No pose or stage injection in this walk. Original walking/standing geometry runs.
	await walk(scene,Vector3(10,0.14,4.5))
	await walk(scene,Setting.STORE_INSIDE)
	check(Base.distance(scene.model.position(),Setting.STORE_INSIDE)<0.6,"door admits the actual player")
	await tap(scene,KEY_F5)
	var saved: Vector3=scene.model.position()
	await walk(scene,Vector3(10,0.14,4.5))
	await tap(scene,KEY_F9)
	check(Base.distance(scene.model.position(),saved)<0.1,"interior save/load retains physical pose")
	await walk(scene,Vector3(10,0.14,4.5))
	await walk(scene,Vector3(-15.5,0.14,6.5))
	await walk(scene,Vector3(-18,0.14,6.5))
	await walk(scene,Vector3(-18,0.14,10.5))
	check(Base.distance(scene.model.position(),Setting.WELL)>1.5,"well can be circumnavigated without teleport")
	await tap(scene,KEY_O)
	check(scene._paused and scene._panel_text.text.contains("RESEARCH / AUTHORING"),"source notebook accessible in actual UI")
	var before: Dictionary=scene.model.snapshot()
	await press(scene,"Clear the haze")
	await frames(20)
	check(scene.model.snapshot()==before,"presentation setting cannot change time, health or character knowledge")
	check(not scene.setting.haze_enabled,"atmosphere can be disabled without disabling geometry")
	await press(scene,"Return")
	# Explicit invalid-pose fixture for the loader, not part of the real route above.
	scene._open_research()
	before=scene.model.snapshot()
	var bad: Dictionary=before.duplicate(true)
	bad.player.position=Base.coords(Setting.WELL)
	bad.actors.ranjit_singh.position=bad.player.position.duplicate()
	var file:=FileAccess.open(SETTING_SAVE,FileAccess.WRITE)
	file.store_string(JSON.stringify(bad,"",true,true));file.close()
	scene._load()
	check(scene.model.snapshot()==before,"well-intersecting save refused without replacing world")
	check(not scene.setting.haze_enabled,"failed load does not reset presentation preference")
	var count: int=scene.setting.get_child_count()
	scene.setting.build(scene)
	check(scene.setting.get_child_count()==count,"repeat build does not duplicate colliders")
	home.queue_free()
	await frames(3)
	home=Launch.make_world()
	scene=home.get_node("ChildhoodChapter")
	scene.save_path=SETTING_SAVE
	root.add_child(home)
	await frames(5)
	check(scene.setting.manifest==manifest,"same seed recreates same retained geometry manifest")
	check(not scene.model.has_economy() and not scene.model.has_road(),"decoration creates no allowance, cargo or political claim")
	home.queue_free()
	await frames()
	for suffix in ["",".tmp",".checkpoint.json"]: DirAccess.remove_absolute(ProjectSettings.globalize_path(SETTING_SAVE+suffix))
	print("GUJRANWALA_SETTING_TESTS: %d passed, %d failed"%[passed,failed])
	quit(1 if failed else 0)
