extends "res://tests/test_gujranwala.gd"
## Focused presentation/contact regression. Complete inquiry and staged actor poses
## below are explicit fixtures; existing test_gujranwala owns the whole supply walk.
const Delivery := preload("res://territory/delivery_presentation.gd")
const STORY_SAVE := "user://delivery-story-regression.json"

func _story_domain() -> void:
	var s := fresh()
	var before := s.snapshot()
	check(Delivery.briefing(s).contains("Four portions"), "dispatch establishes four-part promise")
	check(Delivery.carrier_phase(s) == "locked", "unassigned carrier is not reported active")
	check(s.snapshot() == before, "briefing reads without changing economy or evidence")
	ok(s.operate("accept_delivery"), "fixture dispatch backed by four actual food")
	check(s.economy().ledger.stock.food == 6 and s.economy().ledger.cargo == 4, "four food held once")
	ok(s.save_to(STORY_SAVE), "save before handover")
	var loaded := State.new()
	ok(loaded.load_from(STORY_SAVE), "restore outbound delivery")
	check(loaded.economy().ledger.cargo == 4, "load preserves four portions")
	ok(Pose.pose(loaded, Rules.MARKET), "explicit handover-site fixture")
	ok(loaded.operate("deliver"), "handover admits receipt")
	check(loaded.economy().ledger.purse == 30 and loaded.economy().ledger.treasury == 146, "single original payout")
	check(loaded.economy().ledger.cargo == 0, "handover consumes all carried portions")
	check(Delivery.acknowledgment("deliver", "", loaded).contains("One, two, three, four"), "arrival echoes the actual tally")
	ok(loaded.save_to(STORY_SAVE), "save settled handover")
	ok(s.load_from(STORY_SAVE), "restore settled handover")
	reject(s, s.operate.bind("deliver"), "load cannot repeat delivery reward")
	ok(s.operate("accept_escort"), "assign the same return carrier")
	check(Delivery.carrier_phase(s) == "together", "local carrier assignment begins together")
	var same_carrier: Dictionary = s.economy().merchant.duplicate(true)
	ok(Pose.pose(s, Rules.QUARTERMASTER), "explicit home-alone fixture")
	check(Delivery.carrier_phase(s) == "separated", "home alone is separation, not arrival")
	reject(s, s.operate.bind("checkin"), "home alone cannot finish escort")
	check(s.economy().merchant == same_carrier, "actor fixture never transports carrier")
	check(Delivery.briefing(s).contains("Where is the carrier?"), "home-alone briefing identifies missing person")
	check(Delivery.carrier_transition("together", "separated").begins_with("Buddh"), "separation is own observation, not distant speech")
	check(Delivery.carrier_transition("separated", "together").contains("together"), "regroup offers continuation")
	check(Delivery.carrier_transition("together", "together").is_empty(), "stable travelling never repeats caption")
	check(Delivery.carrier_transition("", "arrived").is_empty(), "initial sampling never invents arrival performance")

func _story_scene() -> void:
	var home := Launch.make_world()
	var scene = home.get_node("ChildhoodChapter")
	scene.save_path = STORY_SAVE
	ok(scene.model.restore(Fixture.complete()), "install explicit completed-inquiry scene fixture")
	root.add_child(home)
	await frames(6)
	look(scene, Rules.QUARTERMASTER)
	await tap(scene, KEY_E)
	check(scene._panel_text.text.contains("coffers feed the household"), "brief allowance in actual dialog")
	await press(scene, "Accept the limited")
	check(scene.model.has_economy(), "local button releases allowance")
	await tap(scene, KEY_E)
	var ledger_before: Dictionary = scene.model.economy().ledger
	look(scene, Rules.QUARTERMASTER + Vector3(0,0,-10))
	await press(scene, "Carry four")
	check(scene.model.economy().ledger == ledger_before, "turning away after opening refuses queued dispatch")
	check(scene._message.contains("face them"), "lost-contact action gives recoverable instruction")
	look(scene, Rules.QUARTERMASTER)
	await tap(scene, KEY_E)
	await press(scene, "Carry four")
	check(scene.model.economy().ledger.cargo == 4, "facing local button dispatches actual cargo")
	check(scene._delivery_load.visible and scene._delivery_load.get_child_count() == 4, "exactly four cosmetic bundles follow cargo")
	for parcel in scene._delivery_load.get_children():
		check(parcel is MeshInstance3D and parcel.get_child_count() == 0, "cargo has no collider or extra simulation")
	ledger_before = scene.model.economy().ledger
	scene._menu_action("econ:accept_delivery")
	await frames(3)
	check(scene.model.economy().ledger == ledger_before, "closed callback cannot reissue cargo")
	# Native save/load and local interactions, with explicit market pose to keep
	# this contact regression separate from the existing full input-driven walk.
	await tap(scene, KEY_F5)
	ok(Pose.pose(scene.model, Rules.MARKET + Vector3(1,0,1)), "explicit market actor fixture")
	scene._apply()
	await frames(5)
	look(scene, Rules.MARKET)
	await tap(scene, KEY_E)
	check(scene._panel_text.text.contains("count together"), "recipient repeats practical promise")
	await press(scene, "Deliver")
	check(not scene._delivery_load.visible and scene.model.economy().ledger.cargo == 0, "parcels disappear only after successful receipt")
	check(scene.model.economy().ledger.purse == 30, "native handover pays original amount once")
	await tap(scene, KEY_F5)
	await tap(scene, KEY_F9)
	check(scene.model.economy().ledger.purse == 30 and not scene._delivery_load.visible, "load of completed handover preserves payment and no cargo")
	ledger_before = scene.model.economy().ledger
	scene._menu_action("econ:deliver")
	await frames(2)
	check(scene.model.economy().ledger == ledger_before, "stale delivery callback after load pays nothing")
	look(scene, Rules.MARKET)
	await tap(scene, KEY_E)
	await press(scene, "Escort a return")
	check(scene.model.economy().ledger.caravan == "active", "native carrier assigned")
	# Standing still lets the physical carrier reach the exact nine-metre limit.
	await frames(340)
	check(Delivery.carrier_phase(scene.model) == "separated", "real carrier motion crosses tether while actor waits")
	check(scene._message.contains("lost contact"), "one short separation cue offers recovery")
	var stopped: Vector3 = scene.merchant.global_position
	var history_count: int = scene.story_attention.history().size()
	await frames(190)
	check(Base.distance(stopped, scene.merchant.global_position) < 0.01, "separated physical carrier remains stopped")
	check(scene.story_attention.history().size() == history_count, "stable separation does not spam scene recall")
	# A clearly declared regroup-position fixture isolates the cue from navigation.
	ok(Pose.pose(scene.model, stopped + Vector3(0,0,2)), "explicit near-carrier regroup fixture")
	scene.avatar.global_position = scene.model.position()
	scene.avatar.velocity = Vector3.ZERO
	look(scene, stopped)
	await frames(8)
	check(Delivery.carrier_phase(scene.model) == "together", "existing local tether is recovered")
	check(scene._message.contains("go on together"), "visible nearby carrier acknowledges reunion")
	await tap(scene, KEY_F5)
	var receipt_count: int = scene.model.economy().events.size()
	await tap(scene, KEY_F9)
	check(scene.model.economy().events.size() == receipt_count, "mid-carrier load adds no arrival or payment receipt")
	check(Delivery.carrier_phase(scene.model) != "arrived", "loading mid-route does not fake arrival")
	# Domain fixture of HOME while carrier remains on route is a check-in refusal.
	ok(Pose.pose(scene.model, Rules.QUARTERMASTER + Vector3(0,0,-1)), "explicit home-alone actor fixture")
	scene._apply()
	await frames(5)
	look(scene, Rules.QUARTERMASTER)
	await tap(scene, KEY_E)
	await press(scene, "Check the physically")
	check(scene.model.economy().ledger.caravan == "active", "native home-alone check-in cannot complete")
	check(scene._message.contains("physically arrive"), "no-arrival refusal is explicit")
	# Explicit arrived-carrier fixture isolates the one-time handover and cosmetic
	# unloading. test_gujranwala proves physical navigation to this same check-in.
	var arrived: Dictionary = scene.model.snapshot()
	arrived.misl.merchant.position = Base.coords(Rules.QUARTERMASTER + Vector3(-2,0,-1))
	arrived.misl.merchant.velocity = [0.0,0.0,0.0]
	ok(scene.model.restore(arrived), "explicit physically-local arrival fixture")
	scene._apply()
	await frames(5)
	look(scene, Rules.QUARTERMASTER)
	await tap(scene, KEY_E)
	check(scene._panel_text.text.contains("load has reached the store"), "arrival briefing uses actual carrier location")
	await press(scene, "Check the physically")
	check(scene.model.economy().ledger.caravan == "complete", "one local check-in resolves carrier trip")
	check(scene.model.economy().ledger.purse == 38 and scene.model.economy().ledger.treasury == 164, "original escort payout settles once")
	check(scene.model.economy().ledger.stock.food == 14 and scene.model.economy().ledger.stock.feed == 16, "same carrier delivers original food and fodder once")
	check(is_equal_approx(scene._carrier_load.position.y, 0.35), "same cosmetic load is put down only after check-in")
	await tap(scene, KEY_F5)
	await tap(scene, KEY_F9)
	ledger_before = scene.model.economy().ledger
	scene._menu_action("econ:checkin")
	await frames(3)
	check(scene.model.economy().ledger == ledger_before, "completed save and stale callback cannot repeat arrival reward")
	check(is_equal_approx(scene._carrier_load.position.y, 0.35), "completed load restores unloaded presentation")
	ok(scene.model.validate(scene.model.snapshot()), "all retained state validates after UI refusal and saves")
	home.queue_free()
	await frames()

func _run() -> void:
	_story_domain()
	await _story_scene()
	for suffix in ["", ".tmp", ".checkpoint.json"]: DirAccess.remove_absolute(ProjectSettings.globalize_path(STORY_SAVE + suffix))
	print("DELIVERY_STORY_TESTS: %d passed, %d failed" % [passed, failed])
	quit(1 if failed else 0)
